name: motherhood_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.0
  audioplayers: ^5.2.1
  http: ^0.13.6
  cached_network_image: ^3.3.0
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^6.0.0
  jwt_decoder: ^2.0.1
  flutter_native_timezone: ^2.0.0
  image_picker: ^1.1.2
  flutter_sound: ^9.6.0  # إضافة مكتبة flutter_sound لتسجيل الصوت
  file_picker: ^5.3.3  # إضافة مكتبة file_picker لاختيار الملفات
  url_launcher: ^6.1.5
  http_parser: ^4.0.2
  path_provider: ^2.0.17
  permission_handler: ^10.4.0
  record: ^5.0.0
  path: ^1.8.0
  flutter_ffmpeg: ^0.4.0
  dio: ^5.3.3
  audio_waveforms: ^1.0.4 
  just_audio: ^0.9.40

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/






  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
